### PR TITLE
Updated all namings to new the one

### PR DESCRIPTION
**Pull request by variananora**
Running the RC-27 will gave you some error because of the old package location.

This will hopefully fixed that.

### CODE REVIEW

**Review by TheBusyBiscuit — COMMENTED** [review]
ooof, now we have a problem. Yeah, this will certainly break metrics on older versions :/
The entire reason why this module exists is too remain version-independent, so that's kinda a deal-breaker...

@WalshyDev any idea on how to tackle this?

**Comment by WalshyDev** [comment]
Not easily :/

There could be some reflection thing and we have a getInstance (which returns Slimefun.getInstance or SlimefunPlugin.getInstance) but, this will add a little bit to the startup time. Not crazy but a bit slower and just makes it more awkward :/

Edit: Actually that wouldn't even work still... No idea honestly. It's gonna be a pain

**Comment by TheBusyBiscuit** [comment]
@WalshyDev What if we make a new repo, e.g. `MetricsModule2`?
Slimefun will then ping that one for updates, whereas older versions will still ping this repo.

**Comment by WalshyDev** [comment]
God that's awkward but yeah, it'll work

**Comment by TheBusyBiscuit** [comment]
Well, archive this one and call it a day, that's what happens to many projects here :LUL:

**Pull request merged**
