### PR TITLE
Add average timing chart

### PR DESCRIPTION
**Pull request by WalshyDev**
The ranges probably should be tweaked. I didn't want big gaps for small amounts but also wanted to know how high it could go. Not sure how I feel about them though.

### CODE REVIEW

**Review by TheBusyBiscuit — COMMENTED** [review]
Some better docs would be cool but looks good to me.

Before approving, one thing:
To circumvent the 15 max problem w ecould have a DrillDownChart instead and use the `PerformanceRating` as a delimiter:
https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/services/profiler/SlimefunProfiler.java#L344-L360

**Comment by WalshyDev** [comment]
We could however if we were to change the PerformanceRating threshold the chart would then change and be weird.

Also not sure exactly how the timings should be per-one. Would be mice to have like 0, 1, 2, 3, etc for `GOOD` and `FINE`. `HURTFUL` would have to be like 25ms per one.
Just a bit awkward to manually specify this if the rating threshold ever changed.

I could instead do like:
```
0-14
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14

15-75
	15-20, 21-25, 26-30, 31-35, 36-40, 41-45, 46-50, 51-55, 56-60, 61-65, 66-70, 71-75

76-150
	76-80, 81-85, 86-90, 91-95, 96-100, 101-105, 106-110, 111-115, 116-120, 121-125, 126-130, 131-135, 136-140, 141-145, 146-150

151-300
	151-160, 161-170, 171-180, 181-190, 191-200, 201-210, 211-220, 221-230, 231-240, 241-250, 251-260, 261-270, 271-280, 281-290, 291-300

301-600
	301-325, 326-350, 351-375, 376-400, 401-425, 426-450, 451-475, 476-500, 501-525, 526-550, 551-575, 576-600

601-1000
	601-650, 651-700, 701-750, 751-800, 801-850, 851-900, 901-950, 951-1000

> 1000
```

**Review by TheBusyBiscuit — APPROVED** [review]

**Comment by TheBusyBiscuit** [comment]
Yeah those would all be too awkward. It should be fine as is, also added it to bStats.
https://bstats.org/plugin/bukkit/Slimefun/4574#average_timings

**Comment by WalshyDev** [comment]
Ooo yay!

**Pull request merged**
